DELETE http://localhost:8080/events/1/register
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZSIsImV4cCI6MTc2NDg1MzA5MSwidXNlcklkIjoxfQ.ivDsd2W7d6kGWlBm9k0PReCjXKEMd9H27ofi6Kk0VmI
